version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root  # Or use jenkins:docker group
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "50000:50000"
