apiVersion: v1
kind: Service
metadata:
  name: todo-list-svc
  labels:
    app: todo-list
spec:
  selector:
    app: todo-list
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080

